# Generated by Django 3.0 on 2022-02-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new',
            new_name='Product',
        ),
    ]
