# Generated by Django 3.0 on 2022-03-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220220_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ign',
            new_name='likes',
        ),
    ]
